name: Compile Latex
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "main.tex"
          args: "-pdf -file-line-error -interaction=nonstopmode"

      - name: Upload Docs to Artifact
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: "main.pdf"
        
      - name: Push to build branch
        run: |
          git config --global user.name 'ChuangSheep'
          git config --global user.email '44814054+ChuangSheep@users.noreply.github.com'
          git checkout build 2>/dev/null || git checkout --orphan build
          git reset
          git add dist -f
          git commit -m "bot: automated build"
          git push origin build --force
